//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZ.Biz
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleType
    {
        public ArticleType()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int id { get; set; }
        public string a_t_ArticleCategory { get; set; }
        public byte a_t_Flag { get; set; }
        public string a_t_CreateBy { get; set; }
        public Nullable<System.DateTime> a_t_CreateDate { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
    }
}
