//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZ.Biz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.LikeCounts = new HashSet<LikeCount>();
        }
    
        public long id { get; set; }
        public string a_Title { get; set; }
        public int a_TypeId { get; set; }
        public string a_KeyWord { get; set; }
        public string a_From { get; set; }
        public string a_Content { get; set; }
        public Nullable<bool> a_IsTop { get; set; }
        public Nullable<bool> a_IsHot { get; set; }
        public Nullable<byte> a_States { get; set; }
        public long a_CreateBy { get; set; }
        public Nullable<System.DateTime> a_CreateDate { get; set; }
        public Nullable<long> a_ModifiedBy { get; set; }
        public System.DateTime a_ModifiedDate { get; set; }
        public Nullable<int> a_Statistics { get; set; }
        public Nullable<int> a_LikeCount { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<LikeCount> LikeCounts { get; set; }
    }
}
