//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZ.Biz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long id { get; set; }
        public long titleID { get; set; }
        public string content { get; set; }
        public Nullable<long> userId { get; set; }
        public string username { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<bool> hasson { get; set; }
        public Nullable<bool> isson { get; set; }
        public Nullable<long> parentid { get; set; }
        public Nullable<int> cool { get; set; }
        public string browserInfo { get; set; }
        public string ipaddress { get; set; }
        public string isp { get; set; }
        public string os { get; set; }
    }
}
