//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZ.Biz
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeCount
    {
        public long l_id { get; set; }
        public long a_id { get; set; }
        public long u_id { get; set; }
        public Nullable<System.DateTime> liketime { get; set; }
        public Nullable<byte> stats { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
