//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZ.Biz
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Articles = new HashSet<Article>();
            this.LikeCounts = new HashSet<LikeCount>();
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public long U_Id { get; set; }
        public System.Guid U_GUID { get; set; }
        public string U_UserName { get; set; }
        public string U_Password { get; set; }
        public string U_Email { get; set; }
        public string U_Salt { get; set; }
        public string U_MobilePhone { get; set; }
        public byte U_State { get; set; }
        public byte U_Access { get; set; }
        public string U_HeadPic { get; set; }
        public Nullable<System.DateTime> U_RegisterDate { get; set; }
        public Nullable<System.DateTime> U_LastLoginTime { get; set; }
        public string U_Tag { get; set; }
        public string U_Signature { get; set; }
        public string U_RealName { get; set; }
        public string U_NickName { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<LikeCount> LikeCounts { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
