//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZ.Biz
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public long id { get; set; }
        public long U_Id { get; set; }
        public string UD_Sex { get; set; }
        public string UD_Age { get; set; }
        public Nullable<System.DateTime> UD_Birth { get; set; }
        public string UD_Cale { get; set; }
        public string UD_Const { get; set; }
        public string UD_BooldType { get; set; }
        public string UD_EmotState { get; set; }
        public string UD_ContactWay { get; set; }
        public string UD_Education { get; set; }
        public string UD_School { get; set; }
        public string UD_PaperType { get; set; }
        public string UD_PaperNumber { get; set; }
        public string UD_Company { get; set; }
        public string UD_Worker { get; set; }
        public string UD_HomeTown { get; set; }
        public string UD_NowPlace { get; set; }
        public string UD_Address { get; set; }
        public string UD_Remark { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
